easy_admin:
  design:
    menu:
      - { label: "Entities" }
      - label: "Products"
        children:
          - { entity: Product, label: "Product List", icon: "th-list" }
      - label: "Category"
        children:
          - { entity: Category, label: "Electronic List", icon: "th-list" }
      - {label: "Settings"}
      - label: "User"
        children:
          - { entity: User, label: "User List", icon: "user", permission: 'ROLE_ADMIN' }
  site_name: 'Electronics Data'
  user:
    display_name: true
    name_property_path: 'name'
  entities:
    # List the entity class name you want to manage
    Product:
      class: App\Entity\Product
      label: "Product"
      form:
        fields:
          - { type: 'group', icon: 'pencil', label: 'Product Field', css_class: 'col-lg-6' }
          - productName
          - description
          - status
          - companyName
          - { type: 'group', icon: 'pencil', label: 'Product Field', css_class: 'col-lg-6' }
          - CreatedAt
          - UpdatedAt
          - category
          - { property: 'thumbnailFile', type: 'vich_image' }
      list:
        collapse_actions: true
        actions: [ 'show', 'edit', 'delete' ]
        batch_actions: [ 'delete' ]
        title: "Product"
        fields: ['productName','description','CreatedAt','category', {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]
#        filters: [ 'status' ]
      show:
        fields:
          - productName
          - status
          - CreatedAt
          - category
          - thumbnail
          - { property: 'thumbnail', type: 'image', base_path: '%uploads_path%' }
    Category:
      class: App\Entity\Category
    User:
      class: App\Entity\User
      list:
        item_permission: 'ROLE_ADMIN'

